# Generated by Django 5.1.2 on 2024-10-19 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1)),
                ('contract_type', models.CharField(choices=[('Full-time', 'Full-time'), ('Part-time', 'Part-time'), ('Temporary', 'Temporary')], max_length=20)),
                ('contract_number', models.CharField(max_length=50, unique=True)),
                ('fathers_name', models.CharField(max_length=50)),
                ('date_of_birth', models.DateField()),
                ('national_id', models.CharField(max_length=10, unique=True)),
                ('place_of_issue', models.CharField(max_length=100)),
                ('contact_number', models.CharField(max_length=20)),
                ('address', models.TextField()),
                ('position', models.CharField(max_length=100)),
                ('contract_start_date', models.DateField()),
                ('contract_end_date', models.DateField()),
                ('base_salary', models.DecimalField(decimal_places=2, max_digits=10)),
                ('housing_allowance', models.DecimalField(decimal_places=2, max_digits=10)),
                ('food_allowance', models.DecimalField(decimal_places=2, max_digits=10)),
                ('seniority_pay', models.DecimalField(decimal_places=2, max_digits=10)),
                ('monthly', models.BooleanField(default=True)),
                ('child_allowance', models.DecimalField(decimal_places=2, max_digits=10)),
                ('marriage_allowance', models.DecimalField(decimal_places=2, max_digits=10)),
                ('transportation_allowance', models.DecimalField(decimal_places=2, max_digits=10)),
                ('attraction_bonus', models.DecimalField(decimal_places=2, max_digits=10)),
                ('management_allowance', models.DecimalField(decimal_places=2, max_digits=10)),
                ('hourly_wage', models.DecimalField(decimal_places=2, max_digits=10)),
                ('hourly_wage_with_accord', models.DecimalField(decimal_places=2, max_digits=10)),
                ('declared_salary', models.DecimalField(decimal_places=2, max_digits=10)),
                ('insurance_type', models.CharField(choices=[('Basic', 'Basic'), ('Comprehensive', 'Comprehensive')], max_length=20)),
                ('job_group', models.CharField(max_length=50)),
                ('account_number', models.CharField(max_length=20)),
                ('bank', models.CharField(max_length=50)),
            ],
        ),
    ]
