# Generated by Django 5.1.2 on 2024-11-13 06:22

import django_jalali.db.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(default='SOME STRING', max_length=255, verbose_name='نام و نام خانوادگی')),
                ('national_id', models.CharField(default='SOME STRING', max_length=10, verbose_name='کد ملی')),
                ('ID_number', models.CharField(default='SOME STRING', max_length=100, verbose_name='شماره شناسنامه')),
                ('date_of_birth', django_jalali.db.models.jDateField(verbose_name='تاریخ تولد')),
                ('place_of_issue', models.CharField(default='SOME STRING', max_length=100, verbose_name='محل صدور')),
                ('fathers_name', models.CharField(default='SOME STRING', max_length=255, verbose_name='نام پدر')),
                ('marital_status', models.CharField(choices=[('متأهل', 'متأهل'), ('مجرد', 'مجرد'), ('مطلقه', 'مطلقه'), ('بیوه', 'بیوه')], default='SOME STRING', max_length=20, verbose_name='وضعیت تاهل')),
                ('child_number', models.DecimalField(decimal_places=0, default=0, max_digits=10, verbose_name='تعداد فرزند')),
                ('contact_number', models.CharField(default='SOME STRING', max_length=15, verbose_name='شماره تماس')),
                ('military_status', models.CharField(choices=[('معاف', 'معاف'), ('در حال خدمت', 'در حال خدمت'), ('پایان خدمت', 'پایان خدمت'), ('نیاز به خدمت ندارد', 'نیاز به خدمت ندارد')], default='SOME STRING', max_length=20, verbose_name='وضعیت نظام وظیفه')),
                ('email', models.EmailField(default='SOME STRING', max_length=254, verbose_name='آدرس ایمیل')),
                ('reference', models.CharField(default='SOME STRING', max_length=255, verbose_name='معرف')),
                ('postal_code', models.CharField(default='SOME STRING', max_length=10, verbose_name='کد پستی')),
                ('address', models.TextField(default='SOME STRING', verbose_name='آدرس')),
                ('contract_type', models.CharField(choices=[('معین', 'معین'), ('شبه معین', 'شبه معین'), ('موقت', 'موقت')], default='SOME STRING', max_length=100, verbose_name='نوع قرارداد')),
                ('contract_number', models.CharField(default='SOME STRING', max_length=50, verbose_name='شماره قرارداد')),
                ('contract_start_date', django_jalali.db.models.jDateField(verbose_name='تاریخ شروع قرارداد')),
                ('contract_end_date', django_jalali.db.models.jDateField(verbose_name='تاریخ پایان قرارداد')),
                ('job_group', models.CharField(choices=[('ستاد', 'ستاد'), ('مدیریت', 'مدیریت'), ('فنی', 'فنی')], default='SOME STRING', max_length=100, verbose_name='گروه کاری')),
                ('job_position', models.CharField(default='SOME STRING', max_length=100, verbose_name='سمت شغلی')),
                ('insurance_type', models.CharField(choices=[('کارفرما', 'کارفرما'), ('کارمند', 'کارمند')], default='SOME STRING', max_length=100, verbose_name='نوع بیمه')),
                ('declared_salary', models.CharField(choices=[('پایه', 'پایه'), ('واقعی', 'واقعی')], default='SOME STRING', max_length=100, verbose_name='حقوق ابرازی')),
                ('base_salary', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='حقوق پایه')),
                ('housing_allowance', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='حق مسکن')),
                ('food_allowance', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='حق خوار و بار')),
                ('seniority_pay', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='پایه سنوات')),
                ('child_allowance', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='حق اولاد')),
                ('marriage_allowance', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='حق تاهل')),
                ('transportation_allowance', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='ایاب و ذهاب')),
                ('attraction_bonus', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='فوق العاده جذب')),
                ('management_allowance', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='حق مدیریت')),
                ('hourly_wage', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='دستمزد ساعتی')),
                ('hourly_wage_with_accord', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='دستمزد ساعتی با آکورد')),
                ('insurance_number', models.CharField(default='SOME STRING', max_length=10, verbose_name='شماره بیمه')),
                ('bank_name_salary', models.CharField(default='SOME STRING', max_length=100, verbose_name='نام بانک حقوق')),
                ('account_number_salary', models.CharField(default='SOME STRING', max_length=100, verbose_name='شماره حساب حقوق')),
                ('IBAN_salary', models.CharField(default='SOME STRING', max_length=100, verbose_name='شماره شبا حقوق')),
                ('bank_name_petty_cash', models.CharField(default='SOME STRING', max_length=100, verbose_name='نام بانک تنخواه')),
                ('account_number_petty_cash', models.CharField(default='SOME STRING', max_length=100, verbose_name='شماره حساب تنخواه')),
                ('IBAN_petty_cash', models.CharField(default='SOME STRING', max_length=100, verbose_name='شماره شبا تنخواه')),
            ],
        ),
    ]
