# Generated by Django 5.1.1 on 2024-12-01 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contract',
            name='IBAN_petty_cash',
        ),
        migrations.RemoveField(
            model_name='contract',
            name='account_number_petty_cash',
        ),
        migrations.RemoveField(
            model_name='contract',
            name='bank_name_petty_cash',
        ),
        migrations.AlterField(
            model_name='contract',
            name='contract_type',
            field=models.CharField(choices=[('معین', 'معین'), ('شبه معین', 'شبه معین'), ('ساعتی', 'ساعتی')], default='SOME STRING', max_length=100, verbose_name='نوع قرارداد'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='hourly_wage_with_accord',
            field=models.DecimalField(decimal_places=2, max_digits=5, verbose_name='درصد آکورد'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='job_group',
            field=models.CharField(choices=[('ستاد', 'ستاد'), ('مدیریت', 'مدیریت'), ('فنی', 'فنی'), ('بازرگانی', 'بازرگانی'), ('دفتر قم', 'دفتر قم')], default='SOME STRING', max_length=100, verbose_name='گروه کاری'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='marital_status',
            field=models.CharField(choices=[('متأهل', 'متأهل'), ('مجرد', 'مجرد')], default='SOME STRING', max_length=20, verbose_name='وضعیت تاهل'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='military_status',
            field=models.CharField(choices=[('معاف شده', 'معاف شده'), ('در حال خدمت', 'در حال خدمت'), ('پایان خدمت', 'پایان خدمت'), ('نیاز به خدمت ندارد', 'نیاز به خدمت ندارد'), ('معافیت تحصیلی', 'معافیت تحصیلی')], default='SOME STRING', max_length=20, verbose_name='وضعیت نظام وظیفه'),
        ),
    ]
