# Generated by Django 5.1.1 on 2024-12-01 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0002_remove_contract_iban_petty_cash_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='degree_of_study',
            field=models.CharField(choices=[('سیکل', 'سیکل'), ('دیپلم', 'دیپلم'), ('فوق دیپلم', 'فوق دیپلم'), ('کارشناسی', 'کارشناسی'), ('کارشناسی ارشد', 'کارشناسی ارشد'), ('دکتری', 'دکتری'), ('فوق دکتری', 'فوق دکتری')], default='SOME STRING', max_length=20, verbose_name='مدرک تحصیلی'),
        ),
        migrations.AddField(
            model_name='contract',
            name='field_of_study',
            field=models.CharField(default='SOME STRING', max_length=255, verbose_name='رشته تحصیلی'),
        ),
    ]
