# Generated by Django 5.1.1 on 2024-12-01 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0003_contract_degree_of_study_contract_field_of_study'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='degree_of_study',
            field=models.CharField(choices=[('سیکل', 'سیکل'), ('دیپلم', 'دیپلم'), ('فوق دیپلم', 'فوق دیپلم'), ('کارشناسی', 'کارشناسی'), ('کارشناسی ارشد', 'کارشناسی ارشد'), ('دکتری', 'دکتری'), ('فوق دکتری', 'فوق دکتری'), ('حوزوی', 'حوزوی')], default='SOME STRING', max_length=20, verbose_name='مدرک تحصیلی'),
        ),
    ]
