# Generated by Django 5.1.1 on 2024-12-01 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0004_alter_contract_degree_of_study'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='hourly_wage_with_accord',
            field=models.IntegerField(verbose_name='درصد آکورد'),
        ),
    ]
