# Generated by Django 5.1.1 on 2024-12-01 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0005_alter_contract_hourly_wage_with_accord'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='attraction_bonus',
            field=models.DecimalField(decimal_places=2, max_digits=20, verbose_name='فوق العاده جذب'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='base_salary',
            field=models.DecimalField(decimal_places=2, max_digits=20, verbose_name='حقوق پایه'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='child_allowance',
            field=models.DecimalField(decimal_places=2, max_digits=20, verbose_name='حق اولاد'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='food_allowance',
            field=models.DecimalField(decimal_places=2, max_digits=20, verbose_name='حق خوار و بار'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='hourly_wage',
            field=models.DecimalField(decimal_places=2, max_digits=20, verbose_name='دستمزد ساعتی'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='housing_allowance',
            field=models.DecimalField(decimal_places=2, max_digits=20, verbose_name='حق مسکن'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='management_allowance',
            field=models.DecimalField(decimal_places=2, max_digits=20, verbose_name='حق مدیریت'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='marriage_allowance',
            field=models.DecimalField(decimal_places=2, max_digits=20, verbose_name='حق تاهل'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='seniority_pay',
            field=models.DecimalField(decimal_places=2, max_digits=20, verbose_name='پایه سنوات'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='transportation_allowance',
            field=models.DecimalField(decimal_places=2, max_digits=20, verbose_name='ایاب و ذهاب'),
        ),
    ]
