# Generated by Django 5.1.6 on 2025-02-25 08:33

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0008_nda_contract_outstanding_contract_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='IBAN_salary',
            field=models.CharField(max_length=100, verbose_name='شماره شبا حقوق'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='ID_number',
            field=models.CharField(max_length=100, verbose_name='شماره شناسنامه'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='account_number_salary',
            field=models.CharField(max_length=100, verbose_name='شماره حساب حقوق'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='address',
            field=models.TextField(verbose_name='آدرس'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='attraction_bonus',
            field=models.DecimalField(decimal_places=0, max_digits=20, verbose_name='فوق العاده جذب'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='bank_name_salary',
            field=models.CharField(max_length=100, verbose_name='نام بانک حقوق'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='base_salary',
            field=models.DecimalField(decimal_places=0, max_digits=20, validators=[django.core.validators.MinValueValidator(1000), django.core.validators.MaxValueValidator(10000000)], verbose_name='حقوق پایه'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='child_allowance',
            field=models.DecimalField(decimal_places=0, max_digits=20, verbose_name='حق اولاد'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='contact_number',
            field=models.CharField(max_length=15, verbose_name='شماره تماس'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='contract_number',
            field=models.CharField(max_length=50, verbose_name='شماره قرارداد'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='contract_type',
            field=models.CharField(choices=[('معین', 'معین'), ('شبه معین', 'شبه معین'), ('ساعتی', 'ساعتی')], max_length=100, verbose_name='نوع قرارداد'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='declared_salary',
            field=models.CharField(choices=[('پایه', 'پایه'), ('واقعی', 'واقعی')], max_length=100, verbose_name='حقوق ابرازی'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='degree_of_study',
            field=models.CharField(choices=[('سیکل', 'سیکل'), ('دیپلم', 'دیپلم'), ('فوق دیپلم', 'فوق دیپلم'), ('کارشناسی', 'کارشناسی'), ('کارشناسی ارشد', 'کارشناسی ارشد'), ('دکتری', 'دکتری'), ('فوق دکتری', 'فوق دکتری'), ('حوزوی', 'حوزوی')], max_length=20, verbose_name='مدرک تحصیلی'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='آدرس ایمیل'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='fathers_name',
            field=models.CharField(max_length=255, verbose_name='نام پدر'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='field_of_study',
            field=models.CharField(max_length=255, verbose_name='رشته تحصیلی'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='food_allowance',
            field=models.DecimalField(decimal_places=0, max_digits=20, verbose_name='حق خوار و بار'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='full_name',
            field=models.CharField(max_length=255, verbose_name='نام و نام خانوادگی'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='hourly_wage',
            field=models.DecimalField(decimal_places=0, max_digits=20, verbose_name='دستمزد ساعتی'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='housing_allowance',
            field=models.DecimalField(decimal_places=0, max_digits=20, verbose_name='حق مسکن'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='insurance_number',
            field=models.CharField(max_length=10, verbose_name='شماره بیمه'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='insurance_type',
            field=models.CharField(choices=[('کارفرما', 'کارفرما'), ('کارمند', 'کارمند')], max_length=100, verbose_name='نوع بیمه'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='job_group',
            field=models.CharField(choices=[('ستاد', 'ستاد'), ('مدیریت', 'مدیریت'), ('فنی', 'فنی'), ('بازرگانی', 'بازرگانی'), ('دفتر قم', 'دفتر قم')], max_length=100, verbose_name='گروه کاری'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='job_position',
            field=models.CharField(max_length=100, verbose_name='سمت شغلی'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='management_allowance',
            field=models.DecimalField(decimal_places=0, max_digits=20, verbose_name='حق مدیریت'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='marital_status',
            field=models.CharField(choices=[('متأهل', 'متأهل'), ('مجرد', 'مجرد')], max_length=20, verbose_name='وضعیت تاهل'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='marriage_allowance',
            field=models.DecimalField(decimal_places=0, max_digits=20, verbose_name='حق تاهل'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='military_status',
            field=models.CharField(choices=[('معاف شده', 'معاف شده'), ('در حال خدمت', 'در حال خدمت'), ('پایان خدمت', 'پایان خدمت'), ('نیاز به خدمت ندارد', 'نیاز به خدمت ندارد'), ('معافیت تحصیلی', 'معافیت تحصیلی')], max_length=20, verbose_name='وضعیت نظام وظیفه'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='national_id',
            field=models.CharField(max_length=10, verbose_name='کد ملی'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='place_of_issue',
            field=models.CharField(max_length=100, verbose_name='محل صدور'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='postal_code',
            field=models.CharField(max_length=10, verbose_name='کد پستی'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='reference',
            field=models.CharField(max_length=255, verbose_name='معرف'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='seniority_pay',
            field=models.DecimalField(decimal_places=0, max_digits=20, verbose_name='پایه سنوات'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='transportation_allowance',
            field=models.DecimalField(decimal_places=0, max_digits=20, verbose_name='ایاب و ذهاب'),
        ),
    ]
